import '../globals.css';
//import HeaderBlog from '@/components/HeaderBlog';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
                {/* <HeaderBlog/> */}

                <main>
                          {children}


                </main>


      </body>
    </html>
  )
}
